### ISSUE TITLE
I can't reproduce the benchmark results in the paper for the model codegen-350

### ISSUE THREAD

**Issue by starlitsky2010** [amazon-science/cceval#10]
Environment: 
transformers             4.29.2

/llm/ckpt/codegen-350/  baseline
```
codegen-350# md5sum *
ce545b7112bec33e4e6c3905deb3753f  added_tokens.json
3481d782bb74d9c281613097144e4eb6  config.json
32975aafd994fe9fcd8ec376f4646f94  download.py
093ecf3f30371012f2e96fcfb10ea6ab  merges.txt
90f42989d722e9976171a5fbdcaa65a0  pytorch_model.bin
90f8f26b12aca56da1b5901ea7f2a4ab  special_tokens_map.json
3a8204890124f8e4d248f4e787f18fa6  tokenizer.json
04e1bb6f6b0315a97fb3956fec246de7  tokenizer_config.json
22377f841debacb023848b3468ea3281  vocab.json
```
It was downloaded from huggingface 

Here is the test script:
```
python eval.py \
         --model_type codelm_cfc \
         --model_name_or_path /llm/ckpt/codegen-350/ \
         --cfc_seq_length 512 \
         --prompt_file ./data/crosscodeeval_data/csharp/line_completion_rg1_bm25.jsonl \
         --gen_length 50 \
         --max_seq_length $max_seq_length \
         --batch_size $batch_size \
         --output_dir $output_dir \
         --dtype $dtype \
        --num_return_sequences 1 \
         --overwrite_cache True \
         --ts_lib ./build/csharp-lang-parser.so \
         --do_sample \
         --top_p 0.95 \
         --temperature 0.2 \
         --num_return_sequences 5 \
         --language csharp
```

Test result:
```
Code Matching: EM 2.94, ES 41.51
ID matching: EM 4.69, Precision 27.23, Recall 23.9, F1 24.24
```

Could  amazon provides some tips about how to reproduce the test results in the paper?

Thanks

**Comment by zijwang** [comment]
Are you trying to reproduce the greedy result? Your args seem to use sampling and have duplicated num_return_sequences --- maybe you can check that first?

**Comment by starlitsky2010** [comment]
Hi @zijwang 

Here are my greedy search test cmds:
```

lang=python
lang=java
lang=typescript
lang=csharp

python eval.py \
        --model_type codelm_cfc \
        --model_name_or_path /store4/users/yuepx1027/llm/codegen-350M-mono \
        --cfc_seq_length 512 \
        --prompt_file ./data/crosscodeeval_data/$lang/line_completion_oracle_bm25.jsonl \
        --gen_length 50 \
        --max_seq_length 2048 \
        --batch_size 16 \
        --output_dir /tmp/crosscodeeval_testrun/ \
        --dtype bf16 \
        --overwrite_cache True \
        --ts_lib ./build/$lang-lang-parser.so \
        --language $lang

```
Then, get the results below:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jlspy/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jlspy/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID   Matching | Python | Java | TypeScript | C#
-- | -- | -- | -- | --
  | EM | F1 | EM | F1 | EM | F1 | EM | F1
Official test result from paper     CodeGen-350M + Retrieval w/ Ref. | 17.49 | 48.14 | 14.68 | 47.9 | 8.85 | 39.75 | 8.88 | 31.27
Local test   result | 17.45 | 48.06 | 12.53 | 41.88 | 6.5 | 34.24 | 6.22 | 27.03
  |   |   |   |   |   |   |   |  
Code Matching | Python | Java | TypeScript | C#
  | EM | ES | EM | ES | EM | ES | EM | ES
Official test result from paper     CodeGen-350M + Retrieval w/ Ref. | 9.64 | 59.331 | 8.04 | 55.75 | 5.21 | 50.25 | 6.5 | 48.58
Local test   result | 9.64 | 60.69 | 5.84 | 54.72 | 3.84 | 48.33 | 4.36 | 46.61



</body>

</html>

Thanks

**Comment by zijwang** [comment]
@starlitsky2010 Thanks for the detailed command.

The issue is that `codegen-350M-mono` is for Python only, and for the rest of languages we use the multilingual version of codegen.

Can you try using `codegen-350M-multi` to see whether you are able to reproduce the results? If it is working as expected, I will update the README to make it intuitive.

**Comment by zijwang** [comment]
@starlitsky2010 The number reported in the paper (Table 7, page 19) for code matching Java ES is 57.75 instead of 55.75. I just reran it on a fresh node and got 

```
Code Matching: EM 8.04, ES 57.86
```

which is close enough to the one reported in the paper. 

Can you double check your results?

**Comment by starlitsky2010** [comment]
@zijwang 

Here is my command:
```
python eval.py \
    --model_type codelm_cfc \
    --model_name_or_path /llm/codegen-350M-multi/ \
    --cfc_seq_length 512 \
    --prompt_file ./data/crosscodeeval_data/java/line_completion_oracle_bm25.jsonl \
    --gen_length 50 \
    --max_seq_length 2048 \
    --batch_size 16  \
    --output_dir /tmp/crosscodeeval_testrun_codegen_java/ \
    --dtype bf16 \
    --overwrite_cache True \
    --ts_lib ./build/java-lang-parser.so \
    --language java
```
I've double confirm it with the results below:
```
Code Matching: EM 7.95, ES 59.70
ID matching: EM 14.63, Precision 50.94, Recall 48.9, F1 48.1
```
Here are md5s for the codegen-350m-multi
```

/llm/codegen-350M-mono# md5sum *
39db61cfa5d3de1e2ca404e5be730b6a  README.md
ce545b7112bec33e4e6c3905deb3753f  added_tokens.json
3481d782bb74d9c281613097144e4eb6  config.json
093ecf3f30371012f2e96fcfb10ea6ab  merges.txt
90f42989d722e9976171a5fbdcaa65a0  pytorch_model.bin
90f8f26b12aca56da1b5901ea7f2a4ab  special_tokens_map.json
3a8204890124f8e4d248f4e787f18fa6  tokenizer.json
04e1bb6f6b0315a97fb3956fec246de7  tokenizer_config.json
22377f841debacb023848b3468ea3281  vocab.json
```

Here is the python-Levenshtein version
```
# pip list | grep "python-Levenshtein"
python-Levenshtein        0.23.0
```

Is there any mistake in the command I provided?


Thanks

**Comment by zijwang** [comment]
@starlitsky2010 QQ: are you using `rapidfuzz`? It sometimes introduces discrepancy in ES metric. If you do use it, try `pip uninstall rapidfuzz -y` then rerun the evaluation?

**Comment by starlitsky2010** [comment]
> @starlitsky2010 QQ: are you using `rapidfuzz`? It sometimes introduces discrepancy in ES metric. If you do use it, try `pip uninstall rapidfuzz -y` then rerun the evaluation?

Yes, you are right. 

After uninstall that package, the result is:

```
Code Matching: EM 7.95, ES 57.86
ID matching: EM 14.63, Precision 50.94, Recall 48.9, F1 48.1
```

Thanks a lot!

**Comment by zijwang** [comment]
No problem. Glad to see it works now.
