### ISSUE TITLE
Retriever performance evaluation

### ISSUE THREAD

**Issue by bsobolev** [amazon-science/cceval#14]
Hello @wasiahmad @zijwang, 
The paper suggests that the framework can be leveraged for retrieval performance evaluation;
However, the repository, as it currently stands, seems to include only pre-generated line completions. For our purposes, we are specifically interested in assessing the performance of various similarity calculation methods within the retrieval process.

Is it possible to get access to the original data and the code used to generate line completion?  
Thanks

**Comment by zijwang** [comment]
Thanks for your interest, @bsobolev .
For raw data, can you please email us? (This is now stated in https://github.com/amazon-science/cceval#requirements)
For retrieval code, we are working on a code release and will post once it is ready.

**Comment by zijwang** [comment]
@bsobolev can you please check #16 to see whether that answers your question?

**Comment by bsobolev** [comment]
@zijwang Thank you so much for getting back to me on this question with the dataset and the scripts!
