### ISSUE TITLE
How is the data set collected? Can you provide some code?

### ISSUE THREAD

**Issue by 18liumin** [amazon-science/cceval#2]

**Comment by zijwang** [comment]
The dataset was collected and cleaned following section 2 in the paper. Please feel free to let us know if you have any specific questions.

**Comment by 18liumin** [comment]
> The dataset was collected and cleaned following section 2 in the paper. Please feel free to let us know if you have any specific questions.
How do I collect the github dataset and clean the data? Can you provide the code?

**Comment by 18liumin** [comment]
> The dataset was collected and cleaned following section 2 in the paper. Please feel free to let us know if you have any specific questions.


How do I collect the github dataset and clean the data? Can you provide the code?

**Comment by 18liumin** [comment]
> > The dataset was collected and cleaned following section 2 in the paper. Please feel free to let us know if you have any specific questions.
> 
> How do I collect the github dataset and clean the data? Can you provide the code?

i want to Collect datasets in other languages

**Comment by zijwang** [comment]
We currently do not have plan to opensource the data collection code. Please feel free to email us if you have interest in extending CrossCodeEval into other languages. Thanks,
