### ISSUE TITLE
how to implement the RG approach?

### ISSUE THREAD

**Issue by 18liumin** [amazon-science/cceval#3]
We tried to use the code made publicly available by the authors of Zhang et al. (2023) but failed to execute them with the provided instructions. As a result, we implemented the RG approach by ourselves. Note that, unlike Zhang et al. (2023), we perform only 1-step retrieval augmented generation. Can you open source the implementation of Repocoder?

**Comment by zijwang** [comment]
We currently do not have the plan to open source the code to run Zhang et al. (2023).
