### ISSUE TITLE
Is there a way to reproduce the gpt-3.5-turbo results with this repo?

### ISSUE THREAD

**Issue by madhavatreplit** [amazon-science/cceval#5]
Hi, 

Thanks for your work and publishing this benchmark!

Had a quick question: is there way that we can use this repo out of the box to evaluate gpt-3.5-turbo out of the box? We saw that you folks numbers for that and wondering if there is a way to evaluate those models using this code base.

Thanks!

**Comment by zijwang** [comment]
We will release that code in the coming weeks. In the meanwhile, feel free to let us know if you have any specific question to that.

**Comment by zijwang** [comment]
@madhavatreplit can you give #6 a try?
cc @pirroh

**Comment by zijwang** [comment]
Hey @madhavatreplit ! Can you let us know whether you got a chance to give the code a try? If it works fine on your end, we will merge it to main.

**Comment by madhavatreplit** [comment]
Hi, I will let you know within 24 hrs!

**Comment by madhavatreplit** [comment]
@zijwang three quick questions:

1.  Did you run the OpenAI model with greedy search for the main results of the benchmark (even though there were "no significant difference between the two" as per Section 3.3 of the paper? Just confirming since the script was defaulting to nucleus sampling.

2. How fast was the evaluation for the OpenAI models? Running the script as it is, we are seeing ~3.8s/it which makes it roughly take 2+ hours. Just wanted to confirm that this in the ballpark you saw and is acceptable and there is no silent bug here.

3. By any chance do you know the exact version of the 3.5 turbo model used? For example, they have `gpt-3.5-turbo-0301`, `gpt-3.5-turbo-0613`, `gpt-3.5-turbo-0301`, `gpt-3.5-turbo-1106`, etc. 

Based on the Arxiv publishing date, I would hazard a guess for `gpt-3.5-turbo-1106`. Not a huge blocker but just in case you knew.

**Comment by nihaljn** [comment]
1. We ran inference using the defaults supplied in the script.
2. While we have not tracked exact time taken for various tasks, 2+ hours is a around the right ballpark. If the stored model outputs look correct, then it should be fine.
3. We most likely used `gpt-3.5-turbo-0613`. Specifying `gpt-3.5-turbo` defaults to the most recent version I believe

**Comment by madhavatreplit** [comment]
Awesome, thank you. We're running evals as we speak. Code looks good. 

The only suggestion I had was that PyPI's default `openai` reference now points to version `1.*`  instead of `0.*`, where the new version has breaking changes. 

I'd suggest adding `openai` to the requirements.txt  and pinning it to the last `0.*` version or the version you ran!

**Comment by zijwang** [comment]
Thanks @madhavatreplit ! We have specificed the version and merged the code into main. Please feel free to let us know if you have further questions.

**Comment by madhavatreplit** [comment]
I am getting back to this now. Is there an easy way to run the evaluation on the generations created by the script?

I tried using `eval.py` out of the box with `--only_compute_metric` (after renaming all the generation files to `predictions.json` which was also needed) and it still shows errors because 'task_id' is not a key. 

Anything I am missing or is the munging and rewriting of a custom evaluation script needed here? Thanks!

**Comment by zijwang** [comment]
@madhavatreplit can you email @nihaljn (nihjain@amazon.com) and me how you run these step-by-step? This might be the easiest way to solve it.

**Comment by zijwang** [comment]
@madhavatreplit we have updated the script in #15. Can you take a look?
