### ISSUE TITLE
Is current crossfile_context provided correctly?

### ISSUE THREAD

**Issue by leiwen83** [amazon-science/cceval#9]
Hi ,

It is indeed impressive work, however I have some confused question to ask here.

Take the first entry of data/crosscodeeval_data/java/line_completion_rg1_bm25.jsonl for example.
Its ground truth is as "int startAngle = ((Arc) object).getStartAngle();" , however there is no hint of getStartAngle being provided in the crossfile_context. So why still we have this entry existed in the dataset?
I mean even as human, I may cannot guess the right output from only the prompt provided...

Thx~

**Comment by wasiahmad** [comment]
Hello, 

In RG1 baseline, we retrieve based on the last "N" lines of the prompt (as query), therefore, the `crossfile_context` retrieved would be relevant (as BM25 defines relevancy), but there is no guarantee that `crossfile_context` would provide hint of the reference. So, we can reach to one of the following two conclusions:
1. If there are hints available within the software project, then the retrieval systems fail to retrieve them.
2. There is no hits available within the software project regarding the reference that can be provided to the model.

Thanks!

**Comment by zijwang** [comment]
@leiwen83 FYI we have also released the data with different retrieval methods (bm25, UniXcoder, OpenAI Ada). Please feel free to give it a try. Let us know if we can help clarify anything else.
